### ISSUE TITLE
Add lowerCaseMapper into mappers

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/xlsx-import#22]
Part of #21 

# TODO:

1. [ ] Create file `src/mappers/lowerCaseMapper.ts` with function matches to type ` (v: string): string`. Which for any input try to return only lower case string.
2. [ ] reexport it in `src/mappers/index.ts`
3. [ ] Prove that it works in unit test (create new one in `tests/unit/mappers.test.ts`)
4. [ ] Describe it in Readme.md (Mappers section doesn't exists, please to add)

## test data provider:

```
const lowerCaseDp = [
  { inValue: '', expectedResult: '' },
  { inValue: 'asd', expectedResult: 'asd' },
  { inValue: 'Asd', expectedResult: 'asd' },
  { inValue: 'ASD', expectedResult: 'asd' },
  { inValue: 'asd ASD', expectedResult: 'asd asd' },
]
```

**Comment by Filipeue** [comment]
is this free to take ?

**Comment by Siemienik** [comment]
@Filipeue yes

**Comment by Siemienik** [comment]
@Filipeue I added the simplest mapper what can I imagine - stringMapper which actaully does nothing:

https://github.com/Siemienik/xlsx-import/blob/9a92510226a4c81d4d7030bc6632e9da8480e2d1/src/mappers/stringMapper.ts#L1-L3

and test for it:

https://github.com/Siemienik/xlsx-import/blob/9a92510226a4c81d4d7030bc6632e9da8480e2d1/tests/unit/mappers/stringMapper.test.ts#L1-L31

It might be nice starting point

**Comment by Metastasis** [comment]
@Siemienik Whats the status? Can I take this one?

**Comment by Filipeue** [comment]
yeah I am sorry, I started another work... @Metastasis you can take this one

**Comment by Metastasis** [comment]
@Filipeue ok 👍

**Comment by Metastasis** [comment]
Done #44

**Comment by Siemienik** [comment]
@Filipeue thank you for an information
@Metastasis nice done :)
