### ISSUE TITLE
Add upperCaseMapper into mappers

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/xlsx-import#23]
Part of #21 

# TODO:

1. [ ] Create file `src/mappers/upperCaseMapper.ts` with function matches to type ` (v: string): string`. Which for any input try to return only upper case string.
2. [ ] reexport it in `src/mappers/index.ts`
3. [ ] Prove that it works in unit test (create new one in `tests/unit/mappers.test.ts`)
4. [ ] Describe it in Readme.md

## test data provider:

```
const upperCaseDp = [
  { inValue: '', expectedResult: '' },
  { inValue: 'asd', expectedResult: 'ASD' },
  { inValue: 'Asd', expectedResult: 'ASD' },
  { inValue: 'ASD', expectedResult: 'ASD' },
  { inValue: 'asd ASD', expectedResult: 'ASD ASD' },
]
```

**Comment by Metastasis** [comment]
@Siemienik 
Can I take this one?

**Comment by Siemienik** [comment]
@Metastasis yes

**Comment by Metastasis** [comment]
Done
PR #36
