### ISSUE TITLE
Add splitMapper into mappers

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/xlsx-import#24]
Part of #21

# TODO:

1. [x] Create file `src/mappers/splitMapper.ts` with function matches to type ` (v: string): string[]`. Which for any input try to return only lower case string.
2. [x] reexport it in `src/mappers/index.ts`
3. [x] Prove that it works in unit test (create new one in `tests/unit/mappers.test.ts`)
4. [x] Describe it in Readme.md 

## test data provider:

```
const lowerCaseDp = [
  { inValue: '', expectedResult: [] },
  { inValue: 'asd', expectedResult: ['asd'] },
  { inValue: 'asd,', expectedResult: ['asd',''] },
  { inValue: 'asd,asd2', expectedResult: ['asd','asd2'] },
  { inValue: 'true,1, expectedResult: ['true','1'] },
]
```

# Further (not in scope of this issue)

* setting for `separator`
* setting for `itemMapper`
