### ISSUE TITLE
Add isEmpty into mappers

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/xlsx-import#37]
Part of #21 

# TODO:

1. [ ] Create file `src/mappers/isEmpty.ts` with function matches to type `ValueMapper<boolean>`. Which examine if input is empty
2. [ ] reexport it in `src/mappers/index.ts`
3. [ ] Prove that it works in unit test
4. [ ] Describe it in Readme.md

## proposed test data provider:

```
const dataProvider = [
  { inValue: '', expectedResult: true },
  { inValue: null, expectedResult: true },
  { inValue: ' ', expectedResult: false }, // it is quite problematic case, however it isn't empty
  { inValue: 'null', expectedResult: false },
  { inValue: 'a', expectedResult: false},
  { inValue: 'as d', expectedResult: false },
]
```

For making a reservation please open draft PR with this issue linked
