### ISSUE TITLE
Add isFilled into mappers

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/xlsx-import#39]
Part of #21 

_It is the opposite of #37 `isEmpty` mapper._

# TODO:

1. [ ] Create file `src/mappers/isFilled.ts` with function matches to type `ValueMapper<boolean>`. Which examine if input is not empty
2. [ ] reexport it in `src/mappers/index.ts`
3. [ ] Prove that it works in unit test
4. [ ] Describe it in Readme.md

## proposed test data provider:

```
const dataProvider = [
  { inValue: '', expectedResult: false },
  { inValue: null, expectedResult: false },
  { inValue: ' ', expectedResult: true }, // it is quite problematic case, however it isn't empty
  { inValue: 'null', expectedResult: true },
  { inValue: 'a', expectedResult: true},
  { inValue: 'as d', expectedResult: true },
]
```

For making a reservation please open draft PR with this issue linked
