### ISSUE TITLE
WIP: Add jsonMapper into mappers

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/xlsx-import#40]
Part of #21 

# TODO:

1. [ ] Create file `src/mappers/jsonMapper.ts` with generic function matches to type **EDIT:** ~`ValueMapper<TJsonResult>`~ `ValueMapper<any>` . Which parse json string into `TJsonResult` and return default `null` when failure.
2. [ ] reexport it in `src/mappers/index.ts` 
3. [ ] Prove that it works in unit test
4. [ ] Describe it in Readme.md

## proposed test data provider:

```js
const dataProvider = [
  { inValue: '', expectedResult: null },
  { inValue: null, expectedResult: null },
  { inValue: ' ', expectedResult: null },
  { inValue: 'asd', expectedResult: null },
  { inValue: 'null', expectedResult: null },
  { inValue: 'false', expectedResult: false },
  { inValue: 'true', expectedResult: true },
  { inValue: '0', expectedResult: 0},
  { inValue: '1', expectedResult: 1},
  { inValue: '"string"', expectedResult: 'string'},
  { inValue: '\'string\'', expectedResult: null},
  { inValue: '{"a":1}', expectedResult: {a:1}},
  { inValue: '{"a":[1]}', expectedResult: {a:[1]}},
]
```

For making a reservation please open draft PR with this issue linked

**Comment by Gontrum** [comment]
Hi @Siemienik, 

Do you have a place where I should add the type TJsonResult? Otherwise I would define it in the jsonMapper.ts and not export it for now.

**Comment by Siemienik** [comment]
Hi @Gontrum, please forgive me that I didn't describe return type clear.

As I mention before, this function should be generic. However the return type `ValueMapper<TJsonResult>` is wrong, sorry about that. 

Right return type is a `JsonMapper<TJsonResult>` which may be defined by `type JsonMapper<TJsonResult> = ValueMapper<TJsonResult|null>`.

Thank you for your PR, I'm going to write a comment there about this 😄

**Comment by Gontrum** [comment]
Hi @Siemienik, thank you for your feedback :-) 

I'm not sure if I got you right, but I have added an alias `JsonMapper` to the `jsonMapper.ts`. Is that what you meant?

**Comment by Siemienik** [comment]
I've just check type, and finally I would recommend to use: `type JsonMapper= <TJsonResult>(value: string) => TJsonResult|null;`

For now, It may be inside of jsonMapper file because any other file do not require it.

**Comment by Siemienik** [comment]
hmm after larger investigation I think that , jsonMapper is enough to has type `ValueMapper<any>`, additionally this make it easier. What fo you think @Gontrum ?

**Comment by Siemienik** [comment]
please look for this comment https://github.com/Siemienik/xlsx-import/pull/43#discussion_r503491653
