### ISSUE TITLE
Add numberMapper into mappers

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/xlsx-import#46]
Part of #21 

# TODO:

1. [ ] Create file `src/mappers/numberMapper.ts` with function matches to type `ValueMapper<number>`. Which parse value string into `number`.
2. [ ] reexport it in `src/mappers/index.ts` 
3. [ ] Prove that it works in unit test
4. [ ] Describe it in Readme.md

## proposed test data provider:

```js
const dataProvider = [
  { inValue: '', expectedResult: NaN },
  { inValue: null, expectedResult: NaN },
  { inValue: '  ', expectedResult: NaN },
  { inValue: '0', expectedResult: 0 },
  { inValue: '000', expectedResult: 0 },
  { inValue: '001', expectedResult: 1 },
  { inValue: '123', expectedResult: 123 },
  { inValue: '123s', expectedResult: 123 },
  { inValue: '0.1', expectedResult: 0.1},
  { inValue: 'a0.1', expectedResult: NaN},
  { inValue: '-1', expectedResult: -1},
  { inValue: '   -1.2123asd', expectedResult: -1.2123}
];
```

## tips:

* I propose to use Number.parseFloat
* For asserting NaN values may be useful isNaN function

For making a reservation please open draft PR with this issue linked

**Comment by Siemienik** [comment]
done in #55
