### ISSUE TITLE
Add integerMapper into Mappers

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/xlsx-import#48]
Part of #21 

# TODO:

1. [ ] Create file `src/mappers/integerMapper.ts` with function matches to type `ValueMapper<number>`. Which parse value string into integer.
2. [ ] reexport it in `src/mappers/index.ts` 
3. [ ] Prove that it works in unit test
4. [ ] Describe it in Readme.md

## proposed test data provider:

```js
const dataProvider = [
  { inValue: '', expectedResult: NaN },
  { inValue: null, expectedResult: NaN },
  { inValue: '  ', expectedResult: NaN },
  { inValue: '0', expectedResult: 0 },
  { inValue: '000', expectedResult: 0 },
  { inValue: '001', expectedResult: 1 },
  { inValue: '123', expectedResult: 123 },
  { inValue: '123.456', expectedResult: 123 },
  { inValue: '123s', expectedResult: 123 },
  { inValue: '0.1', expectedResult: 0},
  { inValue: 'a0.1', expectedResult: NaN},
  { inValue: '-1', expectedResult: -1},
  { inValue: '   -1.2123asd', expectedResult: -1}
];
```

## tips:

* I propose to use Number.parseInt
* For asserting NaN values may be useful isNaN function
* Probably more sense make extract NaN results into another dataProvider - I suppose that may simplify tests code.

For making a reservation please open draft PR with this issue linked

**Comment by machadolucasvp** [comment]
@Siemienik are you sure `integerMapper` should map  `'   -1.2123asd'` to `-1.2123` ?

**Comment by Siemienik** [comment]
> @Siemienik are you sure `integerMapper` should map `' -1.2123asd'` to `-1.2123` ? `parseInt` in this case should and return `-1`

good catch, Sorry that is my mistake - description updated.

**Comment by Siemienik** [comment]
done in #56
