### ISSUE TITLE
Add booleanMapper into mappers

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/xlsx-import#53]
Part of #21 

# TODO:

1. [ ] Create file `src/mappers/booleanMapper.ts` with function matches to type `ValueMapper<boolean>`. Which parse value string into boolean.
2. [ ] reexport it in `src/mappers/index.ts` 
3. [ ] Prove that it works in unit test
4. [ ] Describe it in Readme.md

## proposed test data provider:

```js
const dataProvider = [
  { inValue: null, expectedResult: false },
  { inValue: '', expectedResult: false },
  { inValue: '  ', expectedResult: false },
  { inValue: '0', expectedResult: false },
  { inValue: '000', expectedResult: false },
  { inValue: 'true', expectedResult: false },
  { inValue: 'false', expectedResult: false },
  { inValue: 'a0.1', expectedResult: false},

  { inValue: '001', expectedResult: true },
  { inValue: '123', expectedResult: true },
  { inValue: '0.1', expectedResult: true},
  { inValue: '-1', expectedResult: true},
  { inValue: '   -1.2123asd', expectedResult: true}
];
```

## tips:

* I propose to use `Boolean(Number())`

For making a reservation please open draft PR with this issue linked

**Comment by machadolucasvp** [comment]
Hey @Siemienik, can you please assign this to me?

**Comment by machadolucasvp** [comment]
Hello @Siemienik, are you sure we should expect `inValue: '   -1.2123asd'` be mapped to `true` ?

**Comment by Siemienik** [comment]
> Hello @Siemienik, are you sure we should expect `inValue: ' -1.2123asd'` be mapped to `true` ?

It's quite problematic question, but when I wrote this issue I've follow the result of `Boolean(Number.parseFloat())`. That result true for this input.

**Comment by Siemienik** [comment]
done in #54
